name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## What's Changed
  $CHANGES

  ## Contributors
  $CONTRIBUTORS
change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
version-resolver:
  default: patch
prerelease: false
categories:
  - title: 'Dependency Updates'
    label: 'dependency-update'
exclude-contributors:
  - 'bind-cxeng'
